= eXXcellent programming challenge

This repository provides the project scaffold for a simple
programming challenge. Though the challenge is very simple
and a rather synthetic use-case, your results are helpful
starting point to discuss your programming flavor, skills
and methodology.


== Goal

Implement a solution for the given tasks which aims for

* robustness & correctness
* readability & maintainability
* clean software design & architecture

Be prepared to discuss your implementation and software design
decisions. Show us how you would solve the tasks during your
normal day to day business.

Feel free to come with own ideas & solutions. There is no plain
"right" or "wrong". We are more looking forward to talk to you
about _how_ you achieved your goal, your thoughts and design
idea and process.

If you feel bored by our challenge, please feel free to provide
creative alternative solutions and/or choose other technologies/
languages if you think they would be a better fit.



== Tasks

Weather::
    In `weather.csv` you’ll find daily weather data. Write a
    program to read the file, then output the day number (column one
    `Day`) with the smallest temperature spread (the maximum temperature
    is the second column `MxT`, the minimum the third column `MnT`).

Football::
    The `football.csv` file contains the results from the
    English Premier League. The columns labeled ‘Goals’
    and ‘Goals Allowed’ contain the total number of goals scored
    for and against each team in that season (so Arsenal scored
    79 goals against opponents, and had 36 goals scored against them).
    Write a program to read the file, then print the name of the team
    with the smallest difference in ‘for’ and ‘against’ goals.

Refactoring & Extensibility::
    See if you refactor your code, so that a single program is able
    to solve both questions.

Test Driven Development!::
    Try to follow a test-driven development approach.



== Getting started

.Getting a copy
The starting point is provided as a branch in a Gitlab.com/GitHub
hosted Git repository. Be careful to adjust the URLs below
accordingly.

To start

.Fork or directly clone the repository

```
git clone https://[gitlab|github].com/exxcellent/programming-challenge.git
```
or if you've forked the repository then
```
git clone git@[gitlab|github].com:YOURNAME/programming-challenge.git
```

.Switch to the branch of the challenge assinged
```
cd programming-challenge
git checkout challenge-CHALLENGENAME
```

.Building and running
The project scaffolds provides a Maven `pom.xml` as starting
point. You should be able to start with any IDE or text editor
you are convenient with.

After installing Maven 3.x you should be able to

Run the main class _de.exxcellent.challenge.App_::
    `mvn clean compile exec:java`

Build & test your project::
    `mvn clean test`.

Or use your IDE functionality::
    to run & debug you program.

== Submitting your results
Ideally you provide your solutions as Git repository with
appropriate commits and descriptions. If you have a GitLab.com
or GitHub account, please feel free to publish your solution
there.

If you want feel free to show us your results in advance by
mailing us the URL of your solution.
