= eXXcellent programming challenge

This repository provides the project scaffold for a simple
programming challenge. Though the challenge is very simple
and a rather synthetic use-case, your results are a helpful
starting point to discuss your programming flavor, skills
and methodology.


== Goal

Implement a solution for the given tasks which aims for

* robustness & correctness
* readability & maintainability
* clean software design & architecture

Be prepared to discuss your implementation and software design
decisions. Show us how you would solve the task when working on your day-to-day job.

Feel free to come up with own ideas & solutions. There is no plain
"right" or "wrong". Instead, we want to talk to you
about _how_ you achieved your goal and about your thoughts and design
idea and process.

If you feel bored by our challenge, feel free to provide
creative alternative solutions and/or choose other technologies/
languages, if you think they would be a better fit.



== Task

.Estimated time required
up to ~1 hour


.Task
Implement a function which accepts an arbitrarily nested series of lists i.e. a
List containing other Lists and/or `Integer`
values (`List<?>`). Transform them into a serialized, *flattened*
List of Integers (`List<Integer>`).

Example:: `[1, [2, 3], [4, [5, 6]]]` should become
          `[1, 2, 3, 4, 5, 6]`

The field `de.exxcellent.challenge.App#EXAMPLE_NESTED_LIST`
contains a sample value which you can use as starting point.
Please keep in mind that your application should also be able
to handle any other, sane input.



== Getting started

.Getting a copy
The starting point for every challenge is provided as a branch in a Gitlab.com/GitHub
hosted Git repository. Be careful to adjust the URLs below
accordingly.

To start

.Fork or directly clone the repository

```
git clone https://[gitlab|github].com/exxcellent/programming-challenge.git
```
or if you've forked the repository then
```
git clone git@[gitlab|github].com:YOURNAME/programming-challenge.git
```

See what challenges are available by listing the branches present:
```
git branch -a
```

.Switch to the branch of the challenge assinged
```
cd programming-challenge
git checkout challenge-CHALLENGENAME
```

.Building and running
The project scaffolds provides a Maven `pom.xml` as starting
point. You should be able to start with any IDE or text editor
you are convenient with.

After installing Maven 3.x you should be able to

Run the main class _de.exxcellent.challenge.App_::
    `mvn clean compile exec:java`

Build & test your project::
    `mvn clean test`.

Or use your IDE functionality::
    to run & debug you program.

== Submitting your results

Ideally you provide your solutions as Git repository with
appropriate commits and descriptions. If you have a GitLab.com
or GitHub account, please feel free to publish your solution
there.

If you want feel free to show us your results in advance by
mailing us the URL of your solution.
